### Generated by Claude

import numpy as np
from scipy.integrate import solve_ivp
from itertools import combinations_with_replacement
import matplotlib.pyplot as plt

# ─────────────────────────────────────────────
# 1. GENERATE DATA  (Lorenz system)
# ─────────────────────────────────────────────

def lorenz(t, state, sigma=10, rho=28, beta=8/3):
    x, y, z = state
    return [
        sigma * (y - x),          # ẋ = -10x + 10y
        x * (rho - z) - y,        # ẏ =  28x - y - xz
        x * y - beta * z,          # ż =  xy - (8/3)z
    ]

t_span = (0, 20)
t_eval = np.linspace(*t_span, 4000)
sol = solve_ivp(lorenz, t_span, [1, 1, 1], t_eval=t_eval, rtol=1e-10)

X = sol.y.T          # shape (4000, 3)  — rows are [x, y, z] snapshots

# Add a little noise to make it realistic
rng = np.random.default_rng(42)
X += rng.normal(0, 0.01, X.shape)


# ─────────────────────────────────────────────
# 2. ESTIMATE DERIVATIVES  (finite differences + smoothing)
# ─────────────────────────────────────────────

def smooth_diff(X, t, window=5):
    """Central finite differences with a simple moving-average pre-smooth."""
    # Moving average to reduce noise before differentiating
    kernel = np.ones(window) / window
    X_smooth = np.apply_along_axis(
        lambda col: np.convolve(col, kernel, mode='same'), axis=0, arr=X
    )
    dt = t[1] - t[0]
    dX = np.gradient(X_smooth, dt, axis=0)
    return dX

t = sol.t
dX = smooth_diff(X, t)   # shape (4000, 3)


# ─────────────────────────────────────────────
# 3. BUILD CANDIDATE LIBRARY  Θ(X)
# ─────────────────────────────────────────────

def build_library(X, poly_degree=2, include_trig=False):
    """
    Build a library of candidate functions evaluated on each row of X.
    Returns (Theta, feature_names).
    """
    m, n = X.shape           # m = timesteps, n = state dimension
    features = []
    names = []

    # Constant term
    features.append(np.ones((m, 1)))
    names.append("1")

    # Polynomial terms up to poly_degree
    state_names = ["x", "y", "z"][:n]
    for degree in range(1, poly_degree + 1):
        for combo in combinations_with_replacement(range(n), degree):
            col = np.prod(X[:, combo], axis=1, keepdims=True)
            name = "·".join(state_names[i] for i in combo)
            features.append(col)
            names.append(name)

    if include_trig:
        for i in range(n):
            features.append(np.sin(X[:, i:i+1]))
            names.append(f"sin({state_names[i]})")
            features.append(np.cos(X[:, i:i+1]))
            names.append(f"cos({state_names[i]})")

    Theta = np.hstack(features)   # shape (m, n_features)
    return Theta, names

Theta, feature_names = build_library(X, poly_degree=2)
print(f"Library shape: {Theta.shape}")
print(f"Candidate features ({len(feature_names)}): {feature_names}")


# ─────────────────────────────────────────────
# 4. SPARSE REGRESSION  — Sequential Thresholded Least Squares (STLSQ)
# ─────────────────────────────────────────────

def stlsq(Theta, dX, threshold=0.1, max_iters=20):
    """
    Sequential Thresholded Least Squares.

    Solves  dX ≈ Theta @ Xi  with sparsity enforced by iteratively
    zeroing out small coefficients and refitting on the survivors.

    Returns Xi of shape (n_features, n_states).
    """
    n_features = Theta.shape[1]
    n_states   = dX.shape[1]

    # Initial least-squares solve (all features active)
    Xi = np.linalg.lstsq(Theta, dX, rcond=None)[0]

    for iteration in range(max_iters):
        Xi_old = Xi.copy()

        for j in range(n_states):           # one equation per state variable
            # Find which features survive the threshold
            big = np.abs(Xi[:, j]) >= threshold
            if big.sum() == 0:
                Xi[:, j] = 0
                continue

            # Refit using only surviving features (unbiased estimate)
            Xi[~big, j] = 0
            Xi[big, j] = np.linalg.lstsq(Theta[:, big], dX[:, j], rcond=None)[0]

        # Convergence check
        if np.allclose(Xi, Xi_old, atol=1e-8):
            print(f"  STLSQ converged after {iteration + 1} iterations")
            break

    return Xi

print("\nRunning STLSQ...")
Xi = stlsq(Theta, dX, threshold=0.5)


# ─────────────────────────────────────────────
# 5. READ OFF THE DISCOVERED EQUATIONS
# ─────────────────────────────────────────────

state_names = ["x", "y", "z"]

print("\n── Discovered Equations ──")
for j, sname in enumerate(state_names):
    terms = []
    for i, fname in enumerate(feature_names):
        coef = Xi[i, j]
        if abs(coef) > 1e-6:
            terms.append(f"{coef:+.3f}·{fname}")
    eq = "  ".join(terms) if terms else "0"
    print(f"  d{sname}/dt = {eq}")

print("\n── True Lorenz Equations ──")
print("  dx/dt = -10·x  +10·y")
print("  dy/dt = +28·x  -1·y  -1·xz")
print("  dz/dt = -2.667·z  +1·xy")


# ─────────────────────────────────────────────
# 6. VALIDATE  — simulate with discovered equations
# ─────────────────────────────────────────────

def sindy_rhs(t, state, Xi, feature_names, n_states):
    """Evaluate the SINDy model at a given state."""
    x = np.array(state).reshape(1, -1)
    Theta_x, _ = build_library(x, poly_degree=2)
    dxdt = (Theta_x @ Xi).flatten()
    return dxdt

sol_sindy = solve_ivp(
    sindy_rhs, t_span, [1, 1, 1], t_eval=t_eval,
    args=(Xi, feature_names, 3), rtol=1e-8
)

# ─────────────────────────────────────────────
# 7. PLOT
# ─────────────────────────────────────────────

fig = plt.figure(figsize=(14, 14))
fig.patch.set_facecolor("#0f1117")
# 4 rows: rows 0-2 left = time series, rows 0-1 right = phase portraits,
#         row 3 full width = coefficient bar chart (no overlap with anything)
# Taller height_ratios for rows 0-1 so the 3D plots get more space
gs = fig.add_gridspec(4, 2, height_ratios=[1.6, 1.6, 1.6, 1.2], hspace=0.5, wspace=0.35)

labels = ["x(t)", "y(t)", "z(t)"]
colors_true  = ["#7eb8f7", "#7ef7c4", "#f7c47e"]
colors_sindy = ["#e05c6a", "#e0c05c", "#a05ce0"]

# Time-series comparison — left column, rows 0–2
ax_mask = t_eval < 20
for i in range(3):
    ax = fig.add_subplot(gs[i, 0])
    ax.set_facecolor("#1a1d27")
    ax.plot(t_eval[ax_mask], sol.y[i][ax_mask],
            color=colors_true[i],  lw=1.5, label="True")
    ax.plot(t_eval[ax_mask], sol_sindy.y[i][ax_mask],
            color=colors_sindy[i], lw=1.5, ls="--", label="SINDy")
    ax.set_ylabel(labels[i], color="white")
    ax.tick_params(colors="white")
    ax.spines[:].set_color("#333")
    ax.legend(facecolor="#1a1d27", labelcolor="white", fontsize=8)
    if i == 0:
        ax.set_title("Time-series (t < 20)", color="white", fontsize=11)

# Phase portraits — right column, rows 0–1 only (row 2 right is intentionally empty)
ax3d_true  = fig.add_subplot(gs[0, 1], projection="3d")
ax3d_sindy = fig.add_subplot(gs[1, 1], projection="3d")

for ax, data, title in [
    (ax3d_true,  sol.y,       "True Lorenz"),
    (ax3d_sindy, sol_sindy.y, "SINDy Model"),
]:
    ax.set_facecolor("#1a1d27")
    ax.plot(*data, lw=0.3, alpha=0.7, color="#7eb8f7")
    ax.set_title(title, color="white", fontsize=10)
    ax.tick_params(colors="white")

# Coefficient bar chart — row 3 only, spanning both columns
ax_coef = fig.add_subplot(gs[3, :])
ax_coef.set_facecolor("#1a1d27")
x_pos = np.arange(len(feature_names))
width = 0.25
for j, (sname, color) in enumerate(zip(state_names, colors_true)):
    ax_coef.bar(x_pos + j*width, Xi[:, j], width=width, label=f"d{sname}/dt", color=color)
ax_coef.set_xticks(x_pos + width)
ax_coef.set_xticklabels(feature_names, rotation=45, ha="right", color="white", fontsize=8)
ax_coef.set_title("Discovered Coefficients Ξ", color="white", fontsize=11)
ax_coef.tick_params(colors="white")
ax_coef.spines[:].set_color("#333")
ax_coef.legend(facecolor="#1a1d27", labelcolor="white")
ax_coef.axhline(0, color="#555", lw=0.8)

plt.suptitle("SINDy on the Lorenz System", color="white", fontsize=13, y=1.02)
plt.savefig("SINDy/sindy_lorenz.png", dpi=150, bbox_inches="tight",
            facecolor="#0f1117")
print("\nPlot saved.")